name: Victor
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ccc9b2'
    - '#0b0216'
    - '#625742'
    - '#a49e7c'
    - '#393034'
  brandStrength: 0.6875
  lightness: 0.2202923574950546
  saturation: 0.603983041131869
  rhythmicContrast: 0.4671482676640153
purpose: []
