name: Victor
favicon: null
layout_spectrum: 0.6710484379436821
typography_spectrum: 0.10462095215916634
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8034444293007255
  lightness: 0.2202923574950546
  saturation: 0.603983041131869
  rhythmicContrast: 0.4671482676640153
purpose: []
