layout_spectrum: 0.1311889230273664
typography_spectrum: 0.2731083193793893
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.06166691426187754
  lightness: 0.8187682272400707
  saturation: 0.18950792704708874
  rhythmicContrast: 0.8904551533050835
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Victor Vroegindeweij
  email: victor@victorv.nl
  url: www.victorv.nl
name: Victor
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Victor Vroegindeweij '
description: Documentary Film and Reality Based Advertising
purpose: []
